package kingnalds;

import java.awt.*;
import java.awt.event.*;
import java.awt.geom.*;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.*;

public class InicioFrame extends JFrame {
    private final AppNavigator navigator=new AppNavigator(this);
    private final Map<String,ModernButton> nav=new LinkedHashMap<String,ModernButton>();
    public InicioFrame(){setTitle("KINGNALD'S — Royal Burger House");setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);setMinimumSize(new Dimension(1050,650));setSize(1366,768);setLocationRelativeTo(null);KingdomBackground root=new KingdomBackground();root.setLayout(new BorderLayout());setContentPane(root);root.add(header(),BorderLayout.NORTH);root.add(content(),BorderLayout.CENTER);}
    private JPanel header(){JPanel p=new JPanel(new BorderLayout(20,0));p.setOpaque(false);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(0,0,1,0,new Color(92,70,36)),BorderFactory.createEmptyBorder(11,34,9,34)));JLabel logo=new JLabel("<html><span style='font-size:24px'>KINGNALD'S</span><br><span style='font-family:sans-serif;font-size:8px'>ROYAL BURGER HOUSE</span></html>",new VectorIcon(VectorIcon.Type.CROWN,29,Theme.GOLD),JLabel.LEFT);logo.setIconTextGap(11);logo.setForeground(Theme.IVORY);logo.setFont(Theme.serif(Font.PLAIN,22));p.add(logo,BorderLayout.WEST);JPanel center=new JPanel(new FlowLayout(FlowLayout.CENTER,5,0));center.setOpaque(false);navButton(center,"INICIO",VectorIcon.Type.HOME,navigator::abrirInicio,true);navButton(center,"MENÚ",VectorIcon.Type.MENU,navigator::abrirMenu,false);navButton(center,"PROMOCIONES",VectorIcon.Type.TAG,navigator::abrirPromociones,false);navButton(center,"MIS PEDIDOS",VectorIcon.Type.BAG,navigator::abrirPedidos,false);navButton(center,"MÁS",VectorIcon.Type.MORE,navigator::abrirMas,false);p.add(center,BorderLayout.CENTER);ModernButton cart=new ModernButton("CARRITO",false);cart.setIcon(new VectorIcon(VectorIcon.Type.CART,22,Theme.GOLD));cart.addActionListener(e->navigator.abrirCarrito());p.add(cart,BorderLayout.EAST);return p;}
    private void navButton(JPanel p,String text,VectorIcon.Type icon,Runnable action,boolean active){ModernButton b=new ModernButton(text,false);b.setIcon(new VectorIcon(icon,17,active?Theme.GOLD:Theme.MUTED));b.setForeground(active?Theme.GOLD_LIGHT:Theme.MUTED);b.addActionListener(e->{for(Map.Entry<String,ModernButton> n:nav.entrySet())n.getValue().setForeground(n.getKey().equals(text)?Theme.GOLD_LIGHT:Theme.MUTED);action.run();});nav.put(text,b);p.add(b);}
    private JScrollPane content(){JPanel c=new JPanel();c.setOpaque(false);c.setLayout(new BoxLayout(c,BoxLayout.Y_AXIS));c.setBorder(BorderFactory.createEmptyBorder(18,60,18,60));JLabel title=label("¡BIENVENIDO AL REINO!",Theme.serif(Font.PLAIN,34),Theme.IVORY);title.setAlignmentX(Component.LEFT_ALIGNMENT);c.add(title);JLabel sub=label("Tu próximo banquete te espera.",Theme.sans(Font.PLAIN,13),Theme.MUTED);sub.setAlignmentX(Component.LEFT_ALIGNMENT);c.add(sub);c.add(Box.createVerticalStrut(12));JPanel promos=new JPanel(new GridLayout(1,3,12,0));promos.setOpaque(false);promos.setAlignmentX(Component.CENTER_ALIGNMENT);promos.setMaximumSize(new Dimension(1180,180));promos.add(new PromoCard("MAÑANAS DE LA CORONA","Desayunos disponibles hasta las 11:00 AM","VER DESAYUNOS","/kingnalds/resources/breakfast.png",navigator::abrirDesayunos));promos.add(new PromoCard("EL BANQUETE DEL REY","Almuerzos y cenas desde las 12:00 PM","ORDENAR AHORA","/kingnalds/resources/banquet.png",navigator::ordenarAlmuerzo));promos.add(new PromoCard("SABOR PARA COMPARTIR","Combos reales desde Q45.00","DESCUBRIR","/kingnalds/resources/share.png",navigator::abrirCombos));c.add(promos);c.add(Box.createVerticalStrut(15));JLabel q=label("¿LISTO PARA ORDENAR?",Theme.serif(Font.PLAIN,27),Theme.IVORY);q.setAlignmentX(Component.CENTER_ALIGNMENT);c.add(q);JLabel hint=label("Elige cómo deseas recibir tu banquete",Theme.sans(Font.PLAIN,11),Theme.MUTED);hint.setAlignmentX(Component.CENTER_ALIGNMENT);c.add(hint);c.add(Box.createVerticalStrut(9));JPanel delivery=new JPanel(new GridLayout(1,2,14,0));delivery.setOpaque(false);delivery.setAlignmentX(Component.CENTER_ALIGNMENT);delivery.setMaximumSize(new Dimension(1050,112));delivery.add(new DeliveryCard("/kingnalds/resources/delivery-now.png","PEDIR AHORA","Recíbelo donde estés",navigator::pedirAhora));delivery.add(new DeliveryCard("/kingnalds/resources/schedule-order.png","PROGRAMAR MI PEDIDO","Elige fecha y hora",navigator::programarPedido));c.add(delivery);c.add(Box.createVerticalStrut(13));JLabel footer=label("Precios en quetzales   •   Pago seguro   •   Servicio rápido",Theme.sans(Font.PLAIN,10),Theme.MUTED);footer.setAlignmentX(Component.CENTER_ALIGNMENT);c.add(footer);JScrollPane s=new JScrollPane(c);s.setOpaque(false);s.getViewport().setOpaque(false);s.setBorder(null);s.getVerticalScrollBar().setUnitIncrement(18);return s;}
    private JLabel label(String text,Font font,Color color){JLabel l=new JLabel(text);l.setFont(font);l.setForeground(color);return l;}
}

class KingdomBackground extends JPanel {private final Image image=new ImageIcon(getClass().getResource("/kingnalds/resources/kingdom-background.png")).getImage();protected void paintComponent(Graphics raw){super.paintComponent(raw);Graphics2D g=(Graphics2D)raw.create();g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BICUBIC);double scale=Math.max((double)getWidth()/image.getWidth(this),(double)getHeight()/image.getHeight(this));int w=(int)(image.getWidth(this)*scale),h=(int)(image.getHeight(this)*scale);g.drawImage(image,(getWidth()-w)/2,(getHeight()-h)/2,w,h,this);g.setPaint(new GradientPaint(0,0,new Color(0,0,0,35),0,getHeight(),new Color(0,0,0,170)));g.fillRect(0,0,getWidth(),getHeight());g.dispose();}}

class RoundedPanel extends JPanel {private final Color fill,border;RoundedPanel(Color fill,Color border){this.fill=fill;this.border=border;setOpaque(false);}protected void paintComponent(Graphics raw){Graphics2D g=(Graphics2D)raw.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g.setColor(new Color(0,0,0,115));g.fill(new RoundRectangle2D.Float(5,7,getWidth()-10,getHeight()-10,18,18));g.setColor(fill);g.fill(new RoundRectangle2D.Float(2,2,getWidth()-5,getHeight()-7,18,18));g.setColor(border);g.draw(new RoundRectangle2D.Float(2.5f,2.5f,getWidth()-6,getHeight()-8,18,18));g.dispose();super.paintComponent(raw);}}

class ModernButton extends JButton {private float hover=0,target=0;private final boolean primary;ModernButton(String text,boolean primary){super(text);this.primary=primary;setFont(Theme.sans(Font.BOLD,11));setForeground(primary?Theme.IVORY:Theme.GOLD_LIGHT);setBorderPainted(false);setContentAreaFilled(false);setFocusPainted(false);setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));setIconTextGap(8);setMargin(new Insets(9,14,9,14));addMouseListener(new MouseAdapter(){public void mouseEntered(MouseEvent e){target=1;}public void mouseExited(MouseEvent e){target=0;}});new Timer(16,e->{hover+=(target-hover)*.2f;if(Math.abs(target-hover)<.01f)hover=target;repaint();}).start();}protected void paintComponent(Graphics raw){Graphics2D g=(Graphics2D)raw.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);int lift=getModel().isPressed()?1:Math.round(-2*hover);g.translate(0,lift);Color a=primary?Theme.WINE:new Color(17,17,16),b=primary?Theme.WINE_HOVER:new Color(42,35,24);g.setColor(mix(a,b,hover));g.fill(new RoundRectangle2D.Float(1,2,getWidth()-2,getHeight()-5,9,9));g.setColor(mix(new Color(111,81,38),Theme.GOLD_LIGHT,hover));g.draw(new RoundRectangle2D.Float(1.5f,2.5f,getWidth()-3,getHeight()-6,9,9));g.dispose();super.paintComponent(raw);}private Color mix(Color a,Color b,float t){return new Color((int)(a.getRed()+(b.getRed()-a.getRed())*t),(int)(a.getGreen()+(b.getGreen()-a.getGreen())*t),(int)(a.getBlue()+(b.getBlue()-a.getBlue())*t));}}

class PromoCard extends RoundedPanel {PromoCard(String title,String subtitle,String action,String imagePath,Runnable click){super(new Color(18,15,14,238),new Color(145,106,47));setLayout(new BorderLayout(4,0));setBorder(BorderFactory.createEmptyBorder(13,15,15,8));setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));JPanel copy=new JPanel();copy.setOpaque(false);copy.setLayout(new BoxLayout(copy,BoxLayout.Y_AXIS));copy.add(new JLabel(new VectorIcon(VectorIcon.Type.CROWN,18,Theme.GOLD)));copy.add(Box.createVerticalStrut(2));JLabel h=new JLabel("<html>"+title.replace(" DE "," DE<br>").replace(" PARA "," PARA<br>")+"</html>");h.setFont(Theme.serif(Font.PLAIN,17));h.setForeground(Theme.IVORY);copy.add(h);copy.add(Box.createVerticalStrut(3));JLabel d=new JLabel("<html><div style='width:140px'>"+subtitle+"</div></html>");d.setFont(Theme.sans(Font.PLAIN,9));d.setForeground(Theme.MUTED);copy.add(d);copy.add(Box.createVerticalGlue());ModernButton b=new ModernButton(action,true);b.setAlignmentX(Component.LEFT_ALIGNMENT);b.addActionListener(e->click.run());copy.add(b);add(copy,BorderLayout.CENTER);ProductImage art=new ProductImage(imagePath);art.setPreferredSize(new Dimension(175,145));add(art,BorderLayout.EAST);addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){click.run();}});}}

class ProductImage extends JComponent {private final Image image;ProductImage(String path){java.net.URL url=getClass().getResource(path);if(url==null)throw new IllegalArgumentException("No se encontró el recurso: "+path);image=new ImageIcon(url).getImage();setOpaque(false);}protected void paintComponent(Graphics raw){Graphics2D g=(Graphics2D)raw.create();g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BICUBIC);g.setRenderingHint(RenderingHints.KEY_RENDERING,RenderingHints.VALUE_RENDER_QUALITY);double scale=Math.min((double)getWidth()/image.getWidth(this),(double)getHeight()/image.getHeight(this));int w=(int)(image.getWidth(this)*scale),h=(int)(image.getHeight(this)*scale);g.drawImage(image,(getWidth()-w)/2,getHeight()-h,w,h,this);g.dispose();}}

class DeliveryCard extends RoundedPanel {DeliveryCard(String imagePath,String title,String subtitle,Runnable click){super(new Color(15,15,15,245),new Color(102,76,39));setLayout(new BorderLayout(19,0));setBorder(BorderFactory.createEmptyBorder(14,23,14,23));setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));ProductImage icon=new ProductImage(imagePath);icon.setPreferredSize(new Dimension(94,74));add(icon,BorderLayout.WEST);JLabel text=new JLabel("<html><span style='font-size:17px'>"+title+"</span><br><span style='color:#aaa59b;font-family:sans-serif;font-size:10px'>"+subtitle+"</span></html>");text.setFont(Theme.serif(Font.PLAIN,17));text.setForeground(Theme.IVORY);add(text,BorderLayout.CENTER);ModernButton arrow=new ModernButton("→",false);arrow.setPreferredSize(new Dimension(48,42));arrow.addActionListener(e->click.run());add(arrow,BorderLayout.EAST);addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){click.run();}});}}
